Algoritmo "problema_terreno"

Var

     l, c, m, a, v, p : real


Inicio

      escreva("Digite a largura do terreno: ")
      leia(l)
      escreva("Digite o comprimento do terreno: ")
      leia(c)
      escreva("Informe o valor do metro quadrado: ")
      leia(v)
      
      a <- l * c
      p <- a * v
      
      escreval("Area do terreno = ",a :4:2)
      escreval("Preco do terreno = ",p :4:2)

      



Fimalgoritmo